version: '3.5'

services:
  postgres:
    container_name: brcms-postgres
    hostname: brcms-postgres
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=brcms
      - POSTGRES_USER=brcms
      - POSTGRES_PASSWORD=brcms
    ports:
      - "5432:5432"
    networks:
      - brcms

networks:
  brcms:
    name: brcms
    driver: bridge
