CREATE TABLE IF NOT EXISTS "NODE" (
  "ID"                         VARCHAR(26)      NOT NULL,
  "NAME"                       VARCHAR(255)     NOT NULL,
  "PARENT_ID"                  VARCHAR(26)      NULL,
  "CREATED_AT"                 TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_NODE" PRIMARY KEY ("ID")
);

CREATE UNIQUE INDEX "IX_NODE_NAME_NULL" ON "NODE" ("NAME") WHERE "PARENT_ID" IS NULL;
CREATE UNIQUE INDEX "IX_NODE_NAME_PARENT_ID" ON "NODE" ("NAME", "PARENT_ID");

CREATE TYPE "PROPERTY_TYPE" AS ENUM (
  'TEXT',
  'NUMBER',
  'ARRAY',
  'BOOLEAN',
  'TIMESTAMP',
  'BINARY'
);

CREATE TABLE IF NOT EXISTS "NODE_PROPERTY" (
  "ID"                         VARCHAR(26)      NOT NULL,
  "NODE_ID"                    VARCHAR(26)      NOT NULL,
  "KEY"                        VARCHAR(255)     NOT NULL,
  "TYPE"                       "PROPERTY_TYPE"  NOT NULL,
  "VALUE"                      TEXT             NULL,
  "CREATED_AT"                 TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_NODE_PROPERTY" PRIMARY KEY ("ID")
);

ALTER TABLE ONLY "NODE_PROPERTY"
  ADD CONSTRAINT "FK_NODE_PROPERTY__NODE_ID" FOREIGN KEY ("NODE_ID")
    REFERENCES "NODE" ("ID") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ONLY "NODE"
  ADD CONSTRAINT "FK_NODE__PARENT_ID" FOREIGN KEY ("PARENT_ID")
    REFERENCES "NODE" ("ID") ON DELETE CASCADE ON UPDATE CASCADE;
